[project]
name = "mydjangoapp"
description = "Template django app"
authors = [
    "Endre MÃ¡rk Borza"
]
license = "MIT"
readme = "README.md"
python = ">=3.7"
url = "https://github.com/endremborza/mypackage"
keywords="boilerplate"